### ISSUE TITLE
CMU datasets error

### ISSUE THREAD

**Issue by NamhyeokKim** [gmayday1997/SceneChangeDet#11]
I downloaded cmu dataset and reproduced  the experiments

But some error has occurred in the upsampling step.

Do you know the reason?

documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "train.py", line 282, in <module>
    main()
  File "train.py", line 246, in main
    label_rz_conv5 = Variable(util.resize_label(label.data.cpu().numpy(),size=out_conv5_t0.data.cpu().numpy().shape[2:]).cuda())
  File "/home/nhkim/Desktop/SceneChangeDet/src/utils/utils.py", line 228, in resize_label
    label_resized[:,:,:,:] = interp(labelVar).data.numpy()
  File "/home/nhkim/anaconda3/envs/cosimNet/lib/python2.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nhkim/anaconda3/envs/cosimNet/lib/python2.7/site-packages/torch/nn/modules/upsampling.py", line 131, in forward
    return F.interpolate(input, self.size, self.scale_factor, self.mode, self.align_corners)
  File "/home/nhkim/anaconda3/envs/cosimNet/lib/python2.7/site-packages/torch/nn/functional.py", line 2509, in interpolate
    raise NotImplementedError("Got 5D input, but bilinear mode needs 4D input")
NotImplementedError: Got 5D input, but bilinear mode needs 4D input

**Comment by Tangjunjun0925** [comment]
I got same problem. Have you solved this problem?

**Comment by whuzhangchi** [comment]
Hello, could you please provede me with the CMU dataset download link?

**Comment by abaybek** [comment]
I've got the same error. Does anybody understand the logic behind "resize_label" function?

I assume that an author wanted to resize a label image of size (batch_count x 3 x H x W) to the size of the outer layers. Is it make sense?

**Comment by Li-by** [comment]
> Hello, could you please provede me with the CMU dataset download link?

could you please provede me with the CMU dataset download link? thanks so much

**Comment by basi880830** [comment]
> 

Was it resolved later?
